### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by kshpytsya** [tylerjereddy/pytest-regex#8]
While our current development is done using modern versions of Python we do have to keep supporting the codebase which cannot be switched from Python 3.8 (mostly due to some abandoned scientific libraries which we have to rely on to parse existing model files).
Is the minimal Python version 3.9 a hard requirement for this library due to some feature missing in Python 3.8, or is it just due to the lack of testing on 3.8? We use Poetry for dependency management which leads to inability to install pytest-regex into Python 3.8 environment.

**Comment by tylerjereddy** [comment]
The CI passed with Python 3.8 in gh-9, so I may try to do a release that adds support.

That said, as a general rule I try to follow the mostly agreed-upon community support timelines in https://numpy.org/neps/nep-0029-deprecation_policy.html and the broader stuff in https://scientific-python.org/specs/spec-0000/.

**Comment by kshpytsya** [comment]
Taking a look at the actual code of pytest-regex and how easy it is to add local pytest plugins I have opted for vendoring this plugin in. So it is your call whether you want to release support for 3.8 or not. Kind thanks for prompt reply!

**Comment by tylerjereddy** [comment]
This should be resolved in the latest release: https://github.com/tylerjereddy/pytest-regex/releases/tag/v0.2.0

Which is also available on PyPI now.
